FROM node:23.1.0
RUN set -xe \
  && apt-get update \
  && apt-get install --no-install-recommends -y locales gosu \
  && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
  && dpkg-reconfigure --frontend=noninteractive locales \
  && update-locale LANG=en_US.UTF-8 \
  && rm -rf /var/lib/apt/lists/*

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

WORKDIR /app

COPY package.json *yarn* ./
RUN yarn install



COPY . .
# COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
# RUN chmod +x /usr/local/bin/docker-entrypoint.sh

#tutti possono usare i node modules (777)
RUN chmod 777 /app/node_modules
# ENTRYPOINT [ "/usr/local/bin/docker-entrypoint.sh" ]

CMD ["yarn", "start"]